in: 
	g++ -I. -I/usr/local/systemc-2.3.1/include -L. -L/usr/local/systemc-2.3.1/lib-linux64 -Wl,-rpath=/usr/local/systemc-2.3.1/lib-linux64 -o vidproc input.cpp filter.cpp  -lsystemc -lm `pkg-config --cflags --libs opencv`
